#!/usr/bin/env python

"""a playground script where I try to sample from a hierarchical model
"""
__author__ = "Reed Essick (reed.essick@gmail.com)"

#-------------------------------------------------

from jax import random

import numpyro
import numpyro.distributions as dist
from numpyro.infer import (MCMC, NUTS)

#-------------------------------------------------

raise NotImplementedError('''\
sample from a hierarchical model in which all the priors and distributions of parameters are modeled by analytic functions from numpyro.distributions

Then, when you're comfortable with that, try a model in which the observed data come from a different distribution that is not analytically known --> something like an observed set of (weighed) PE samples?
''')
